- name: create /etc/redis
  file:
    path: "/etc/redis"
    state: "directory"
    mode: 0750
- name: Copying configuration file
  register: output
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
- name: Deploy Redis Stack Server
  community.docker.docker_container:
    name: redis
    image: redis/redis-stack-server:latest
    ports:
      - "{{ hostvars[inventory_hostname]['port'] }}:6379"
    detach: true
    pull: yes
    restart_policy: always
    # restart: yes
    volumes:
      - /etc/redis/redis.conf:/redis-stack.conf:rw
      - /etc/redis/local-data/:/data:rw
