- name: create /etc/redis
  file:
    path: "/etc/redis"
    state: "directory"
    recurse: "yes"
    mode: 0750
- name: Copying configuration file
  register: output
  template:
    src: sentinel.conf.j2
    dest: /etc/redis/sentinel.conf
