- name: create /etc/redis
  file:
    path: "/etc/redis"
    state: "directory"
    recurse: "yes"
    mode: 0750
- name: Copying configuration file
  register: output
  template:
    src: sentinel.conf.j2
    dest: /etc/redis/sentinel.conf
- name: Deploy Sentinel Server
  community.docker.docker_container:
    name: sentinel
    image: redis/redis-stack-server:latest
    ports:
      - {{ hostvars[inventory_hostname]['sentinel_port'] }}:26379
    detach: true
    pull: yes
    restart_policy: always
    volumes:
      - /etc/redis:/etc/redis:rw
    command: redis-sentinel /etc/redis/sentinel.conf
