version: '3.3'
services:
  redis-0:
    image: redis/redis-stack-server:latest
    restart: always
    volumes:
      - "./redis-0/redis.conf:/redis-stack.conf"
      - "./local-data/:/data"
    ports:
      - 6380:6379
  sentinel-0:
    image: redis/redis-stack-server:latest
    restart: always
    volumes:
      - "./sentinel-0:/etc/sentinel"
    command: redis-sentinel /etc/sentinel/sentinel.conf
    network_mode: "host"