version: '3.3'
services:
  redis-2:
    image: redis/redis-stack-server:latest
    restart: always
    volumes:
      - "./redis-2/redis.conf:/redis-stack.conf"
      - "./local-data/:/data"
    ports:
      - 6382:6379
  sentinel-2:
    image: redis/redis-stack-server:latest
    restart: always
    volumes:
      - "./sentinel-2:/etc/sentinel"
    command: redis-sentinel /etc/sentinel/sentinel.conf
    ports:
      - 26382:26379